### PR TITLE
Fixed Segfault for reference types

### LINKED ISSUE #980: ODIN_II: Segfault when connecting output port to vector element
Related Issue #848 

#### Expected Behaviour
Should be able to connect output port to vector element.
If this is not possible, Odin II should at least provide a meaningful error or warning message to help the developer to debug their code.

#### Current Behaviour
Odin II exits with a segfault, with no meaningful error or warning message

#### Steps to Reproduce
Run Odin II with the verilog file provided by @MohamedElgammal
[top.v.txt](https://github.com/verilog-to-routing/vtr-verilog-to-routing/files/3644440/top.v.txt)
Original Repo: https://github.com/MohamedElgammal/Odin-issues/tree/master/seg_fault

```
--------------------------------------------------------------------
Welcome to ODIN II version 0.1 - the better High level synthesis tools++ targetting FPGAs (mainly VPR)
Email: jamieson.peter@gmail.com and ken@unb.ca for support issues

--------------------------------------------------------------------
High-level synthesis Begin
Parser starting - we'll create an abstract syntax tree. Note this tree can be viewed using Grap Viz (see documentation)
Adding file ../../../Odin-issues/seg_fault/top.v to parse list
[1]    8722 segmentation fault (core dumped)  ./odin_II -V ../../../Odin-issues/seg_fault/top.v

```
##### Workaround
wire temp1;
wire temp2;
assign out[0] = temp1;
assign out[1] = temp2;

and(temp1, in1[0],in2[0]);
and(temp2, in1[1],in2[1]);
```
--------------------------------------------------------------------
Welcome to ODIN II version 0.1 - the better High level synthesis tools++ targetting FPGAs (mainly VPR)
Email: jamieson.peter@gmail.com and ken@unb.ca for support issues

--------------------------------------------------------------------
High-level synthesis Begin
Parser starting - we'll create an abstract syntax tree. Note this tree can be viewed using Grap Viz (see documentation)
Adding file ../../../Odin-issues/seg_fault/top.v to parse list
Optimizing module by AST based optimizations
Converting AST into a Netlist. Note this netlist can be viewed using GraphViz (see documentation)
==========================
Detected Top Level Module: 	and2
==========================
Performing Optimizations of the Netlist
Performing Partial Map to target device
Outputting the netlist to the specified output format
Successful High-level synthesis by Odin
	Blif file available at default_out.blif
	Ran in 1.3ms
--------------------------------------------------------------------
--------------------------------------------------------------------
Odin ran with exit status: 0
Odin II took 0.00 seconds (max_rss 4.5 MiB)
```

##### uname -a
```
Linux JBpc 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```
##### gcc -v
```
gcc version 9.1.0 (GCC) 
```

### PR DESCRIPTION
**Pull request by djns99**
Fixes when creating gates with reference types with no identifier name.

#### Related Issue
Fixes #980 

#### How Has This Been Tested?
Added tests for basic vector reference type using both multiple and single gate input types

#### Types of changes
- [x] Bug fix (change which fixes an issue)

#### Checklist:
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by djns99** [comment]
@jeanlego I tried to regenerate the QOR files for the simulation with
`make sanitize && ./verify_odin.sh -j 6 --regenerate_qor -t regression_test/benchmark/task/micro micro/vector_and/k6_frac_N10_frac_chain_mem32K_40nm micro/vector_and/k6_N10_40nm micro/vector_and/k6_N10_mem32K_40nm micro/vector_and/no_arch micro/vector_buf/k6_frac_N10_frac_chain_mem32K_40nm micro/vector_buf/k6_N10_40nm micro/vector_buf/k6_N10_mem32K_40nm micro/vector_buf/no_arch` but this regenerated everything. Do you know what I am doing wrong?

**Comment by djns99** [comment]
Also are there other test cases that would be good to have. I believe this bug applies to all the reference types - not just the basic case I have tests for

**Comment by jeanlego** [comment]
> @jeanlego I tried to regenerate the QOR files for the simulation with
> `make sanitize && ./verify_odin.sh -j 6 --regenerate_qor -t regression_test/benchmark/task/micro micro/vector_and/k6_frac_N10_frac_chain_mem32K_40nm micro/vector_and/k6_N10_40nm micro/vector_and/k6_N10_mem32K_40nm micro/vector_and/no_arch micro/vector_buf/k6_frac_N10_frac_chain_mem32K_40nm micro/vector_buf/k6_N10_40nm micro/vector_buf/k6_N10_mem32K_40nm micro/vector_buf/no_arch` but this regenerated everything. Do you know what I am doing wrong?

nothing, it's currently something I have not worked out. To generate individual lines would mean extra logic that has not been implemented in the script. for now, we have to resort to regenerating all the files (at least it is not all of them). For the few cycles needed on each task, I haven't found the necessity to do it yet.

**Comment by djns99** [comment]
Where do the tests belong? Im not really sure where I should be putting them, I dont feel micro is correct.

**Comment by jeanlego** [comment]
> Also are there other test cases that would be good to have. I believe this bug applies to all the reference types - not just the basic case I have tests for

both test seem to exercise the parse_to_ast functions, this seems sufficient for the changes provided.

I think this can only affect gates since they are the only one that can be instantiated without names

**Comment by djns99** [comment]
I dont know it has anything to do with gates. Its that the name of the reference type is not in the same place.
Also I tested with bit ranges and hit an assertion - I assume that is not expected behaviour?

**Comment by jeanlego** [comment]
> Where do the tests belong? Im not really sure where I should be putting them, I dont feel micro is correct.

I would do syntax since it is exercising the Verilog syntax more than anything else.
Eventually this needs to be cleaned up and reorganized a bit better. 

## operators
exercises keyword and basic arithmetic and syntax support,all test should be green. 
(mostly to test FLEX and simple BISON)

## arch_sweep
verify that odin does support a large array of architecture 
(ARCH parse and basic hard block parsing capability).

## syntax
verify that the syntax is respected 
(exercise BISON and parse_to_ast)

## cmd_line_params
check that extra arguments to odin are still working and prevent future breakage 
(somewhat, needs to be polished i.e. check that file is created etc...)

## Micro
This is the one where if its not any of the above.. it goes here

## Full
This is for the benchmarks that are large (more than 15-20 seconds to synthesize)
but still small enough to be simulated for regression without running them in parralel.

## Large
We don't simulate these during regression testing due to their size and we cannot run them in paralel

**Comment by jeanlego** [comment]
I see that it fixed one of the failing benchmark!
I would double check 
```diff
  Ok . . . . . . . . . . . . . . . . . syntax/ifdef-else-syntax/k6_frac_N10_frac_chain_mem32K_40nm
  Failed . . . . . . . . . . . . . . . syntax/bm_dag7_mod_log/k6_frac_N10_frac_chain_mem32K_40nm
    - Po                                  [--1-]{+3+}
    - latch                               [--1-]{+0+}
    - logic element                       [--1-]{+3+}
    - Multiplier                          [--1-]{+0+}
    - Average Path                        [--1-]{+3+}
    - Pi                                  [--1-]{+6+}
    - Adder                               [--1-]{+0+}
    - Estimated LUTs                      [--1-]{+3+}
    - Total Node                          [--1-]{+3+}
    - Memory                              [--1-]{+0+}
    - Latch Drivers                       [--1-]{+0+}
    - exit                                [-1.0-]{+0.0+}
    - Longest Path                        [--1-]{+3+}
  Ok . . . . . . . . . . . . . . . . . syntax/bm_DL_nbit_adder_with_carryout_and_overflow_simplified/no_arch
```

If possible, only add/edit the changes you produce on the csv. i.e. these two lines and the one produced from the new verilog
```csv
syntax/bm_dag7_mod_log/k6_frac_N10_frac_chain_mem32K_40nm                                       , k6_frac_N10_frac_chain_mem32K_40nm.xml, bm_dag7_mod_log.v                                       , 1   , -1          , -1           , -1                , -1           , -1 , -1 , -1           , -1   , -1   , -1        , -1    , -1     , 4                 , -1          , -1          , -1            , -1        
syntax/bm_dag7_mod_log/no_arch                                                                  , n/a                                   , bm_dag7_mod_log.v                                       , 1   , -1          , -1           , -1                , -1           , -1 , -1 , -1           , -1   , -1   , -1        , -1    , -1     , -1                , -1          , -1          , -1            , -1        
```

I do agree that we need to only change the cells needed, not the whole file.
the parse_result.py has to be able to produce a diff'd csv.
could you open an issue against that ^  and you can self assign if you have spare cycles and need it, otherwise I will try to get to it. 
It would definetly make for better regression diff's

**Comment by jeanlego** [comment]
> I dont know it has anything to do with gates. Its that the name of the reference type is not in the same place.
> Also I tested with bit ranges and hit an assertion - I assume that is not expected behaviour?

apologies, I misread that, then yes definitely needs to be checked if it is not already done.

File: ODIN_II/SRC/parse_making_ast.cpp [hunk 1]
```diff
@@ -1355,7 +1362,14 @@ ast_node_t* newMultipleInputsGateInstance(char* gate_instance_name, ast_node_t*
         symbol_node = newSymbolNode(gate_instance_name, line_number);
     }
 
-    char* newChar = vtr::strdup(expression1->types.identifier);
+    char* newChar;
+    if (expression1->types.identifier) {
+        newChar = vtr::strdup(expression1->types.identifier);
+    } else {
+        oassert(expression1->num_children > 0);
+        oassert(expression1->children[0]->type == IDENTIFIERS && "Expected child to be an identifier");
```
Comment (jeanlego) [inline ODIN_II/SRC/parse_making_ast.cpp]: I think it would be better to be a separate function -> get_instance_port_identifier()
in it I would check if it is a RANGE_REF or an ARRAY_REF then look for the symbol at ->children[0]

the assert are not essential since it should not get there unless the bison is messed up.

My biggest worry is
```
`define REVERSE 0
module and2 (in1,in2,out);
input  [1:0] in1,in2;
output [1:0] out;

and((REVERSE)?out[0]:out[1], in1[0],in2[0]);
and(out[1], in1[1],in2[1]);
endmodule 
```

this should be allowed if i am not mistaken Verilog 2005 but correct me if i am wrong

Comment (jeanlego) [reply ODIN_II/SRC/parse_making_ast.cpp]: I think it is better to leave the tree as is at that stage, and only check the port name when it is needed, we can build the circuitry later if we can't resolve the condition (a mux) or it will be folded in one of the phases.

Comment (djns99) [reply ODIN_II/SRC/parse_making_ast.cpp]: My opinion is that asserts are essential whenever there is a sentence that starts with 'we should not get here unless...' (that's kinda the point of them)

Comment (djns99) [reply ODIN_II/SRC/parse_making_ast.cpp]: > I think it is better to leave the tree as is at that stage, and only check the port name when it is needed, we can build the circuitry later if we can't resolve the condition (a mux) or it will be folded in one of the phases.

Do you mean that we should get rid of the check

```
for (long j = 0; j < list_of_module_items->num_children && variable_found == false; j++) {
    if (list_of_module_items->children[j]->type == VAR_DECLARE_LIST) {
        for (long k = 0; k < list_of_module_items->children[j]->num_children; k++) {
            if (strcmp(list_of_module_items->children[j]->children[k]->children[0]->types.identifier, module_variables_not_defined[i]->children[0]->children[0]->types.identifier) == 0)
                variable_found = true;
        }
    }
}
if (!variable_found)
    add_child_to_node_at_index(list_of_module_items, module_variables_not_defined[i], 0);
else
    free_whole_tree(module_variables_not_defined[i]);
```
and then do that later?

Or do you mean merge this fix and then make it work for more complicated expressions later?

Comment (jeanlego) [reply ODIN_II/SRC/parse_making_ast.cpp]: correct.
[IEEE.1364-2005](http://staff.ustc.edu.cn/~songch/download/IEEE.1364-2005.pdf):: pg 173 
section **12.3 Ports** it shows concat and say any valid expression as port.

expecting a certain subtree and doing constant folding on ternary etc.. becomes a bit more involved for this phase (parsing into an ast).
ast optimization should fold any foldable logic and leave you with something you can work with after.
At that point, if the subtree is not just a symbol, array_ref or range_ref (concatenations may resolve weirdly... I remember this being an issue) you can build logic and do hookup directly since the names would be for the subexpressions rather than the port directly.

Comment (jeanlego) [reply ODIN_II/SRC/parse_making_ast.cpp]: I can work with this as a bug fix, but a proper fix is still needed (and should be used by most of everything using ports).
this will also simplify things when we work on scoping issues

Comment (djns99) [reply ODIN_II/SRC/parse_making_ast.cpp]: Ok so should I raise a separate issue for compound statements as the output for a port. And we can merge this to fix for vector types?

**Comment by jeanlego** [comment]
we use clang-format for formatting the codebase. the .clang-format is in the root of the repo.
Once you get the format fixed I can merge

File: ODIN_II/SRC/parse_making_ast.cpp (hunk 1 above)
Comment (jeanlego) [reply ODIN_II/SRC/parse_making_ast.cpp]: correct.
It does fix the initial issue and it is an improvement.

as for the regression diffs,  #1247 should fix parts of the problem

**Comment by djns99** [comment]
@jeanlego We should be good to go once Travis finishes. Sorry for the delay

**Comment by jeanlego** [comment]
Np :)
