### PR TITLE
Track non-configurable edge usage to enable pruning.

### LINKED ISSUE #526: Router generating "stub" or "antenna" nets
#### Expected Behaviour

Router only enables muxes on paths to sinks

#### Current Behaviour

Router generates some "stub" or "antenna" nets that do not connect to a sink.

#### Possible Solution

I haven't investigated too deeply, first step was to create an issue describing the problem.

#### Steps to Reproduce
1. Unzip [vpr_bug3.zip](https://ufile.io/a6jpf)
2. Run:
```
vpr \
 arch.unique_pack.xml \
 top.eblif \
 --device xc7a50t-basys3-test --read_rr_graph rr_graph_xc7a50t-basys3_test.rr_graph.real.xml \
 --min_route_chan_width_hint 100 --max_criticality 0.0 --max_router_iterations 500 --routing_failure_predictor off --router_high_fanout_threshold -1 \
 --constant_net_method route --route_chan_width 500 --clock_modeling route --place_algorithm bounding_box --enable_timing_computations off \
 --allow_unrelated_clustering on --route
```

#### Analysis

Example stub is at rr node 433885.  Analysis that shows its a stub:

```
# Pretty print rr graph for ease of grepping
$ xmllint --format rr_graph_xc7a50t-basys3_test.rr_graph.real.xml > t.xml
# Relevant node
$ grep -C 3 INT_L_X14Y124.SE6BEG1.LOGIC_OUTS_L23 t.xml
    </edge>
    <edge sink_node="433885" src_node="421075" switch_id="2">
      <metadata>
        <meta name="fasm_features">INT_L_X14Y124.SE6BEG1.LOGIC_OUTS_L23</meta>
      </metadata>
    </edge>
    <edge sink_node="1094822" src_node="421075" switch_id="2">
# Find node in route
$ grep -n 433885 top.route
2574:Node:	433885	 CHANX (40,27) to (44,27)  Track: 110  Switch: 3
# Walk graph following node 433885 to sinks.  switch_id="3" are shorts
$ grep src_node=\"433885 t.xml
    <edge sink_node="433884" src_node="433885" switch_id="3"/>
$ grep src_node=\"433884 t.xml
    <edge sink_node="433886" src_node="433884" switch_id="3"/>
    <edge sink_node="433885" src_node="433884" switch_id="3"/>
# So 433884, 433885 and 433886 are shorted to each other
# 433886 contains the edges to other nodes in the graph
$ grep src_node=\"433886 t.xml
    <edge sink_node="433884" src_node="433886" switch_id="3"/>
    <edge sink_node="636697" src_node="433886" switch_id="2">
    <edge sink_node="636705" src_node="433886" switch_id="2">
    <edge sink_node="1101336" src_node="433886" switch_id="2">
    <edge sink_node="1101342" src_node="433886" switch_id="2">
    <edge sink_node="1101386" src_node="433886" switch_id="2">
    <edge sink_node="637940" src_node="433886" switch_id="2">
    <edge sink_node="1038942" src_node="433886" switch_id="2">
    <edge sink_node="1101401" src_node="433886" switch_id="2">
    <edge sink_node="1101280" src_node="433886" switch_id="2">
    <edge sink_node="635773" src_node="433886" switch_id="2">
    <edge sink_node="1101287" src_node="433886" switch_id="2">
    <edge sink_node="1101156" src_node="433886" switch_id="2">
    <edge sink_node="1100588" src_node="433886" switch_id="2">
    <edge sink_node="433614" src_node="433886" switch_id="2">
    <edge sink_node="433906" src_node="433886" switch_id="2">
    <edge sink_node="433927" src_node="433886" switch_id="2">
# Grep each downstream node and see if it part of the same net
$ grep -n 636697 top.route 
$ grep -n 636705 top.route 
11852:Node:	636705	 CHANX (44,31) to (53,31)  Track: 33  Switch: 2
$ grep -n 1101336 top.route 
$ grep -n 1101342 top.route 
11777:Node:	1101342	 CHANX (44,31) to (45,31)  Track: 206  Switch: 2
$ grep 1101386 top.route 
Node:	1101386	 CHANY (44,30) to (44,31)  Track: 237  Switch: 2
Node:	1101386	 CHANY (44,30) to (44,31)  Track: 237  Switch: 3
$ grep -n 1101386 top.route 
11728:Node:	1101386	 CHANY (44,30) to (44,31)  Track: 237  Switch: 2
11734:Node:	1101386	 CHANY (44,30) to (44,31)  Track: 237  Switch: 3
$ grep -n 637940 top.route 
$ grep -n 1038942 top.route 
$ grep -n 1101401 top.route 
$ grep -n 1101280 top.route 
11595:Node:	1101280	 CHANY (44,31) to (44,32)  Track: 254  Switch: 2
11602:Node:	1101280	 CHANY (44,31) to (44,32)  Track: 254  Switch: 3
$ grep -n 635773 top.route 
$ grep -n 1101287 top.route 
$ grep -n 1101156 top.route 
$ grep -n 1100588 top.route 
$ grep -n 433614 top.route 
$ grep -n 433906 top.route 
$ grep -n 433927 top.route 
```

All downstream nodes are members of different nodes, therefore shorted node group (433884, 433885, 433886) is an stub or antenna.

#### Your Environment
VTR built from https://github.com/SymbiFlow/vtr-verilog-to-routing/commit/d8c2e526c3bbc09172ca5b6f3bb2e3cf9524c20b

### PR DESCRIPTION
**Pull request by litghost**
#### Description

The previous pruning code left non-configurable sets unpruned.  The new code tracks outbound configurable edges from non-configurable sets, and prunes them when the count reaches zero.

Fixes #526

#### Related Issue

- #526

#### How Has This Been Tested?

 - [x] Check route has been updated to detect stubs
 - [x] Symbiflow designs that were failing with the new check route now do not error
 - [ ] CI is green

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by litghost** [comment]
@kmurray : I'm working on a fix for the CI failure, but what do you think of the general strategy?

**Comment by kmurray** [comment]
As alluded to in #526, I'm not sure this is the right fix. As the failure indicates:

```
        > Error 1: 
	> Type: Routing
	> File: /home/travis/build/verilog-to-routing/vtr-verilog-to-routing/vpr/src/route/check_route.cpp
	> Line: 707
	> Message: Illegal routing for net 'paj_raygentop_hierarchy_no_mem^globalreset' (#840) some required non-configurably connected nodes are missing:
	>   Missing RR node: 27070 type: CHANX location: (1,4) <-> (2,4) track: 13 len: 1 longline: 0 seg_type: unnamed_segment_0 dir: DEC_DIR
	>   Missing RR node: 27148 type: CHANX location: (3,4) <-> (6,4) track: 13 len: 3 longline: 0 seg_type: unnamed_segment_0 dir: DEC_DIR
	>   Missing RR node: 27218 type: CHANX location: (7,4) <-> (10,4) track: 13 len: 3 longline: 0 seg_type: unnamed_segment_0 dir: DEC_DIR
```
it looks like this change causes nodes within a non-configurably connected node set to be pruned which is not legal.

The definition/invariant of non-configurable edges is that all nodes connected by them must be all used together. Only using parts of them is inconsistent with what they are trying to model (i.e. that the tool can not choose to use only parts of them).

**Comment by litghost** [comment]
> As alluded to in #526, I'm not sure this is the right fix. As the failure indicates:
> 
> ```
>         > Error 1: 
> 	> Type: Routing
> 	> File: /home/travis/build/verilog-to-routing/vtr-verilog-to-routing/vpr/src/route/check_route.cpp
> 	> Line: 707
> 	> Message: Illegal routing for net 'paj_raygentop_hierarchy_no_mem^globalreset' (#840) some required non-configurably connected nodes are missing:
> 	>   Missing RR node: 27070 type: CHANX location: (1,4) <-> (2,4) track: 13 len: 1 longline: 0 seg_type: unnamed_segment_0 dir: DEC_DIR
> 	>   Missing RR node: 27148 type: CHANX location: (3,4) <-> (6,4) track: 13 len: 3 longline: 0 seg_type: unnamed_segment_0 dir: DEC_DIR
> 	>   Missing RR node: 27218 type: CHANX location: (7,4) <-> (10,4) track: 13 len: 3 longline: 0 seg_type: unnamed_segment_0 dir: DEC_DIR
> ```

This was actually caused by a bug in how the non-configurable sets were being created.  The previous sets were just wrong.

**Comment by litghost** [comment]
I've seen this result in a some negative router behavior in some Symbiflow iteration tests.  I'm going to modify the PR to only prune after routing is complete, but before check route.

**Comment by kmurray** [comment]
After staring at the code for a while I think I now understand both what the original issue was, and what this PR does to address it.

**Original Problem**
The original route tree pruning code would correctly avoid partially pruning nodes which were non-configurably connected together (which would be illegal given the definition of non-configurability). However was too conservative and _did not_ prune whole non-configurably connected node sets when they no longer fanned out to any SINKs.

**This PR**
- Adds a stub checker to check route, which errors if route tree branches do not connect to SINKs
- Adds tracking of how many SINKs in a particular route tree connect through sets of non-configurably connected nodes
- Explicitly prunes non-configurably connected node sets who connect to no SINKs

@litghost Is my understanding correct?

@litghost A bit more context about what caused the issue and how this PR resolves it would have been helpful :)

**Comment by litghost** [comment]
> @litghost Is my understanding correct?

Yes.  There is also:

 - A change to how the non-configurable sets are formed to ensure that the sets are correct.

File: vpr/src/route/route_tree_timing.cpp [hunk 1]
```diff
@@ -1010,6 +1055,21 @@ t_rt_node* prune_route_tree_recurr(t_rt_node* node, CBRR& connections_inf, bool
...
+        //      node set
+        //
+        //      -- and --
+        //
+        //   3. The node set is not active
+        //
+        //  Then prune this node.
+        if (non_config_node_set_usage != nullptr && node_set != -1 && device_ctx.rr_switch_inf[node->parent_switch].configurable() && (*non_config_node_set_usage)[node_set] == 0) {
+            // This node should be pruned, re-prune edges once more.
+            return prune_route_tree_recurr(node, connections_inf, /*force_prune=*/false, non_config_node_set_usage);
```
Comment (kmurray) [inline vpr/src/route/route_tree_timing.cpp]: The condition here seems correct.

Maybe I'm missing something, but its not immediately clear to me how the call to prune_route_tree_recurr() with force_prune=false actually causes the node set to be pruned. Wouldn't it just be a no-op? The conditions which brought us to this branch of prune_route_tree() with the current node haven't changed.

File: vpr/src/route/route_tree_timing.h [hunk 2]
```diff
@@ -49,11 +49,14 @@ void print_route_tree_node(const t_rt_node* rt_root);
...
 
-t_rt_node* traceback_to_route_tree(t_trace* head);
 t_rt_node* traceback_to_route_tree(ClusterNetId inet);
+t_rt_node* traceback_to_route_tree(ClusterNetId inet, std::vector<int>* non_config_node_set_usage);
+t_rt_node* traceback_to_route_tree(t_trace* head);
+t_rt_node* traceback_to_route_tree(t_trace* head, std::vector<int>* non_config_node_set_usage);
 t_trace* traceback_from_route_tree(ClusterNetId inet, const t_rt_node* root, int num_remaining_sinks);
 
 t_rt_node* prune_route_tree(t_rt_node* rt_root, CBRR& connections_inf);
+t_rt_node* prune_route_tree(t_rt_node* rt_root, CBRR& connections_inf, std::vector<int>* non_config_node_set_usage);
```
Comment (kmurray) [inline vpr/src/route/route_tree_timing.h]: We should have comments which clarify what the difference is between the versions which take `non_config_node_set_usage`, and those which don't.

For `traceback_to_route_tree()` I think it just records the node set usage (number of sinks connected via each set).

For `prune_troute_tree()` its less clear. Does the version without `non_config_node_set_usage` prune unused node sets or not? If they have different behaviour we should either give them different names or make very clear comments to that effect.

**Comment by litghost** [comment]
> From my reading of the code it looks like pruning is still occurring in prune_route_tree() which is being called during routing. Can you clarify how it is disabled during routing?

Non-configurable node set pruning only occurs if non-configurable node set usage is provided.  If `non_config_node_set_usage == nullptr`, then non-configurable node set pruning is not done.

File: vpr/src/route/route_tree_timing.cpp (hunk 1 above)
Comment (litghost) [reply vpr/src/route/route_tree_timing.cpp]: If the following is true: 
- The node set is unused (e.g. `(*non_config_node_set_usage)[node_set] == 0`)
- This particular node still had children (which is true by virtue of being in this else statement)

Then that indicates that the node set became unused during the pruning.  One or more of the children of this node will be prune if prune_route_tree_recurr is called again.

Consider:
```
1 -> 2
2 -> 3 [non-configurable]
2 -> 4 [non-configurable]
3 -> 5
4 -> 6
```

Assume that nodes 5 and 6 do *not* connect to a sink, so they will be pruned (as normal).  When `prune_route_tree_recurr` visits 2 for the first time, node 3 or 4 will remain.  This is because when `prune_route_tree_recurr` visits 3 or 4, it will *not* have visited 4 or 3 (respectively).  As a result, either node 3 or 4 will not be pruned on the first pass, because the node set usage count will be > 0.  However after `prune_route_tree_recurr` visits 2, 3 and 4, the node set usage will be 0, so everything can be pruned.

Comment (kmurray) [reply vpr/src/route/route_tree_timing.cpp]: OK that makes more sense. I think we need more comments to discuss this case, probably including your example.

**Comment by kmurray** [comment]
> Non-configurable node set pruning only occurs if non-configurable node set usage is provided. If `non_config_node_set_usage == nullptr`, then non-configurable node set pruning is not done.

I think this needs to be clarified in the code, since it is a fairly significant different behavioural difference.

File: vpr/src/route/route_tree_timing.h (hunk 2 above)
Comment (litghost) [reply vpr/src/route/route_tree_timing.h]: I've updated the comments, let me know if you want further changes.

**Comment by litghost** [comment]
> I think this needs to be clarified in the code, since it is a fairly significant different behavioural difference.

Ya, done.

File: vpr/src/route/route_tree_timing.cpp (hunk 1 above)
Comment (litghost) [reply vpr/src/route/route_tree_timing.cpp]: I've added this example for now.  If we can come up with a pithy'er comment, we can shorted it.

**Comment by litghost** [comment]
> in the RR graph, and isn't pruned (until the end) it would be unusable to any other net, potentially preventing a legal routing from being found.

The pruning code already prunes non-configurable sets if the node is congested, so this is already handled?

**Comment by kmurray** [comment]
OK sounds good! Thanks for the fix.
